### ISSUE TITLE
Report on whether the artist is accused (or convicted) of gender violence

### ISSUE THREAD

**Issue by martinszy** [QuickLyric/QuickLyric#257] opened 2020-02-23 04:46 UTC
Hi, I'm thinking this app has all what's needed to notify users if the music they are listening is made by rapists or other types other gender-based violence.

There's a desktop filter for mp3 files here: https://0xacab.org/faras/machecker

Maybe a similar approach can be taken for android, based on the source for this app. If you agree we can start with a fork.

**Comment by geecko86** [comment] 2020-02-23 10:30
Hey Martin,

Thanks for the suggestion. Do you have a similar link in English (or even French)? I can't really investigate your suggestion otherwise.

At the time of writing this comment, I certainly like the idea of condemning artists that are guilty of such violence. However I do wonder what the legal consequences might be, and I don't really have a lawyer at hand.

**Comment by martinszy** [comment] 2020-02-25 19:18
Hey, glad to hear you like the idea.

So you can read the link with google translation, here: https://translate.google.com/translate?hl=&sl=es&tl=fr&u=https%3A%2F%2F0xacab.org%2Ffaras%2Fmachecker

The software scrapes the website tuidoloesunforro.com.ar, which is a well maintained database of gender-based violence cases in the show bussiness. All the reports are in spanish. In the metadata you have some information about what type of violence it was and what's the stage of the accusation. It's not limited to spanish speaking artists. I don't know a more complete database.

So this is scraped and published in this JSON file: https://0xacab.org/faras/machecker/-/raw/master/forros_filter.json

There you have the name, the tags of the accusation and the link to the report, which in turn has more links to sources.

Regarding the legality of all this, it's just collecting publicly available information regarding public persons and publishing it, the website takes good care of not misrepresenting the cases, and they do remove cases which are found to be baseless. So I think this is enough to say the source is trustable.

Regarding your interface, just saying "there's a public accusation" would be enough to alert users and fair to people who might be unjustly accused.

What do you think?

**Comment by geecko86** [comment] 2020-02-25 19:57
So I clicked your link, scrolled down a bit, saw "Axl Rose" and clicked the link.

* The page is in Spanish. No problem, I translated it - but it means I can't use the text to explain why the artist is problematic.

* More problematic is the fact that the translated text reads as follow:

> In the book "The Last of the Giants: The True Story of Guns N 'Roses," journalist Mick Wall, alleges that Axl Rose and Slash raped a 15-year-old girl.

For the reason I mentioned above, I am not comfortable labeling an artist as rapist (etc.) based on what is essentially hearsay. The dataset does not clearly differentiate between allegations and information. You mentioned the idea of simply using the word "accusation", which might be a solution.. but it's not exactly great either.

* The dataset contains entries for persons, not for the bands they play in. For instance, it has entries for Anthony Kiedis (Red Hot Chili Peppers) and Axl Rose (Guns 'N Roses), but it does not make the connection to band they play in. QuickLyric would not be able to automatically display warnings for the bands those people play in. In other words, **I don't think this dataset is usable as is**.

**Comment by martinszy** [comment] 2020-02-25 20:06
Here's more evidence about the case: https://www.ultimate-guitar.com/news/general_music_news/how_axl_rose_avoided_statutory_rape_charge_from_a_15-year-old_girl.html

Which seems to have been brought to the justice but never tried, which, you know, it's very hard for this types of cases and was even harder a few years ago. But the article I'm sending now, which is not part of the original dataset, has a quote by slash that confirms statutory rape in this case. Which brings me back to saying that this dataset is trustworthy.

I would love it if we had another dataset, in enlgish, which had more metadata and more sources, but for now this is the best I know, and I think it's good enough and could be replaced in the future when a better one emerges. What do you think?

**Comment by geecko86** [comment] 2020-02-25 20:09
As I said, the main thing is that Axl Rose (to use him as an example again) is not the artist name. The artist name is "Guns 'N Roses" so there's no way to even use this dataset, unless we're talking about solo artists.

I would also want to link the users to a page where they can get more information. I am not comfortable with simply saying "There is a public accusation" without backing up the claim. I cannot do that, since the only available link is in Spanish.

Again, the idea and the cause is great, the tools are not.

**Comment by martinszy** [comment] 2020-02-25 20:14
Yes, we would need another dataset that links bands to their members. There should be one like that probably, right?

And regarding the language of the claims, they can be linked to a translated version in the user's language 

I see you're open to it and just caring for the quality of your product. So please leave this issue open so we can find better tools, ok?

**Comment by martinszy** [comment] 2020-02-25 22:49
I have found the MusicBrainz public API contains information on arist-to-band relations, for example Axl Rose: https://musicbrainz.org/ws/2/artist/db4da9ba-c52b-4df9-876f-7c6db3582256?inc=artist-rels

Here's the documentation: https://musicbrainz.org/doc/Development/XML_Web_Service/Version_2

Do you think this solves it?

**Comment by geecko86** [comment] 2020-03-05 04:12
To sum things up, the tools we would need are:

* A functional artists database that identifies a-holes
* Providing the user with an explanation as to why the artist is problematic

Based on the discussion we had in this thread, I can say that:

* The database exists, but has issues. It could be possible (although we haven't tested this) to work around the main issue by using MusicBrainz. Obviously this would require additional work within our infrastructure.
* An explanation as to why the artist is marked can only be provided in Spanish, which can then be auto-translated. Auto-translation is risky in itself, and is also a paid service.

Those are enormous compromises and would require hours of work for something which, at the end of the day, is essentially displaying content within QuickLyric without us having a quality control over it.

After consulting with fellow feminists, I decided I would close the issue. Part of me believes in this idea but as of right now, given the above compromises, it doesn't seem feasible.

**Closed as completed by geecko86** 2020-03-05 04:12 UTC
